<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Laravel Paladin Enabled
    |--------------------------------------------------------------------------
    |
    | This option controls whether the Paladin self-healing system is enabled.
    | When disabled, the paladin:heal command will exit without processing.
    |
    */

    'enabled' => env('PALADIN_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | Log Monitoring Configuration
    |--------------------------------------------------------------------------
    |
    | Configure which log channels and levels Paladin should monitor for issues.
    | By default, it monitors standard Laravel log channels for errors and above.
    |
    */

    'log' => [
        'channels' => env('PALADIN_LOG_CHANNELS', 'stack,single'),
        'levels' => ['error', 'critical', 'alert', 'emergency'],
        'storage_path' => storage_path('logs'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Issue Detection & Analysis
    |--------------------------------------------------------------------------
    |
    | Configure how Paladin categorizes and prioritizes issues from logs.
    | Severity mapping determines the priority order for fixing issues.
    |
    */

    'issues' => [
        'max_per_run' => env('PALADIN_MAX_ISSUES_PER_RUN', 5),
        'severity_mapping' => [
            'emergency' => 'critical',
            'alert' => 'critical',
            'critical' => 'critical',
            'error' => 'high',
        ],
        'ignore_patterns' => [
            // Add regex patterns to ignore specific log entries
            // Example: '/Package .* is abandoned/',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Worktree Configuration
    |--------------------------------------------------------------------------
    |
    | Git worktrees are used to isolate fix attempts. Configure where they
    | are created and how they are managed.
    |
    */

    'worktree' => [
        'base_path' => env('PALADIN_WORKTREE_PATH', '../paladin-worktrees'),
        'naming_pattern' => 'paladin-fix-{issue_id}-{timestamp}',
        'cleanup_after_success' => true,
        'cleanup_after_days' => 7,
    ],

    /*
    |--------------------------------------------------------------------------
    | OpenCode Integration
    |--------------------------------------------------------------------------
    |
    | Configure how Paladin integrates with OpenCode for automated fixes.
    | Auto-install will attempt to install OpenCode if not found.
    |
    */

    'opencode' => [
        'binary_path' => env('PALADIN_OPENCODE_PATH', 'opencode'),
        'auto_install' => env('PALADIN_OPENCODE_AUTO_INSTALL', true),
        'timeout' => 600, // 10 minutes
    ],

    /*
    |--------------------------------------------------------------------------
    | Testing & Verification
    |--------------------------------------------------------------------------
    |
    | Configure how Paladin verifies that fixes work correctly.
    | Tests must pass for a fix to be considered successful.
    |
    */

    'testing' => [
        'command' => env('PALADIN_TEST_COMMAND', 'php artisan test'),
        'timeout' => 300, // 5 minutes
        'max_fix_attempts' => env('PALADIN_MAX_FIX_ATTEMPTS', 3),
        'require_passing_tests' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Git Configuration
    |--------------------------------------------------------------------------
    |
    | Configure git branch naming, commit messages, and PR templates.
    |
    */

    'git' => [
        'default_branch' => env('PALADIN_DEFAULT_BRANCH', 'main'),
        'branch_prefix' => 'paladin/fix',
        'commit_message_template' => '[Paladin] Fix: {issue_title}

{issue_description}

Severity: {severity}
Attempt: {attempt_number}/{max_attempts}
Auto-generated by Laravel Paladin',
        'pr_title_template' => '[Paladin] Fix: {issue_title}',
        'pr_body_template' => '## 🛡️ Automated Fix by Laravel Paladin

### Issue Details
- **Type**: {issue_type}
- **Severity**: {severity}
- **Affected Files**: {affected_files}

### Description
{issue_description}

### Fix Attempt
- **Attempt**: {attempt_number} of {max_attempts}
- **Tests Status**: ✅ Passing

### Stack Trace
```
{stack_trace}
```

---
*This PR was automatically generated by [Laravel Paladin](https://github.com/DerKekser/laravel-paladin)*',
    ],

    /*
    |--------------------------------------------------------------------------
    | Pull Request Providers
    |--------------------------------------------------------------------------
    |
    | Configure the default provider and credentials for creating pull requests.
    | Supported: 'github', 'azure-devops', 'mail'
    |
    */

    'pr_provider' => env('PALADIN_PR_PROVIDER', 'github'),

    'providers' => [
        'github' => [
            'token' => env('PALADIN_GITHUB_TOKEN'),
            'api_url' => env('PALADIN_GITHUB_API_URL', 'https://api.github.com'),
        ],

        'azure-devops' => [
            'organization' => env('PALADIN_AZURE_DEVOPS_ORG'),
            'project' => env('PALADIN_AZURE_DEVOPS_PROJECT'),
            'token' => env('PALADIN_AZURE_DEVOPS_PAT'),
            'api_url' => env('PALADIN_AZURE_DEVOPS_URL', 'https://dev.azure.com'),
        ],

        'mail' => [
            'to' => env('PALADIN_MAIL_TO'),
            'from' => env('PALADIN_MAIL_FROM', env('MAIL_FROM_ADDRESS')),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Laravel AI Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the AI provider and models used for analysis and prompt generation.
    | Gemini is recommended for cost-effectiveness and capability.
    |
    */

    'ai' => [
        'provider' => env('PALADIN_AI_PROVIDER', 'gemini'),
        'model_analysis' => env('PALADIN_AI_MODEL_ANALYSIS', 'gemini-2.0-flash-exp'),
        'model_prompts' => env('PALADIN_AI_MODEL_PROMPTS', 'gemini-2.0-flash-exp'),
        'temperature' => 0.7,
    ],

    /*
    |--------------------------------------------------------------------------
    | Queue Configuration
    |--------------------------------------------------------------------------
    |
    | Configure whether healing should run in the background queue.
    |
    */

    'queue' => [
        'enabled' => env('PALADIN_QUEUE_ENABLED', true),
        'connection' => env('PALADIN_QUEUE_CONNECTION'),
        'queue' => env('PALADIN_QUEUE_NAME', 'default'),
    ],

];
